live_config_reload = true
working_directory = "None"
keyboard.bindings = [
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[bell]
animation = "EaseOutCirc"
color = "0x464d6a"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#24273a"
foreground = "#cad3f5"
dim_foreground = "#8087a2"
bright_foreground = "#cad3f5"

[colors.cursor]
text = "#24273a"

[colors.vi_mode_cursor]

[colors.search.matches]
foreground = "#24273a"
background = "#a5adcb"

[colors.search.focused_match]
foreground = "#24273a"
background = "#a6da95"

[colors.footer_bar]
foreground = "#24273a"
background = "#a5adcb"

[colors.hints.start]
foreground = "#24273a"
background = "#eed49f"

[colors.hints.end]
foreground = "#24273a"
background = "#a5adcb"

[colors.selection]
text = "#24273a"
background = "#f4dbd6"

[colors.normal]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"

[colors.bright]
black = "#5b6078"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#a5adcb"

[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "block"

[font]
size = 16
normal = { family= "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family= "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family= "JetBrainsMono Nerd Font", style = "MediumItalic" }
bold_italic = { family= "JetBrainsMono Nerd Font", style = "BoldItalic"}

[selection]
save_to_clipboard= false

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 500
multiplier = 3

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = true
opacity = 0.6
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
